--- Makefile	2015-07-13 18:31:19.000000000 +0300
+++ Makefile	2015-07-16 12:26:03.205861548 +0300
@@ -7,9 +7,6 @@
 packetbeat: $(GOFILES)
 	go build
 
-go-daemon/god: go-daemon/god.c
-	make -C go-daemon
-
 .PHONY: with_pfring
 with_pfring:
 	go build --tags havepfring
@@ -32,28 +29,26 @@
 
 .PHONY: updatedeps
 updatedeps:
-	godep update ...
+	$(GOPATH)/bin/godep update ...
 
 .PHONY: install
-install: packetbeat go-daemon/god
-	install -D packetbeat $(DESTDIR)/$(BIN_PATH)/packetbeat
-	install -D go-daemon/god $(DESTDIR)/$(BIN_PATH)/packetbeat-god
+install: packetbeat-$(VERSION)
+	install -D packetbeat-$(VERSION) $(DESTDIR)/$(BIN_PATH)/packetbeat
 	install -m 644 -D etc/packetbeat.yml $(DESTDIR)/$(CONF_PATH)/packetbeat.yml
 	install -m 644 -D etc/packetbeat.template.json $(DESTDIR)/$(CONF_PATH)/packetbeat.template.json
 
 .PHONY: dist
-dist: packetbeat go-daemon/god
+dist: packetbeat-$(VERSION)
 	mkdir packetbeat-$(VERSION)
-	cp packetbeat packetbeat-$(VERSION)/
-	cp go-daemon/god packetbeat-$(VERSION)/packetbeat-god
+	cp packetbeat-$(VERSION) packetbeat-$(VERSION)/
 	cp etc/packetbeat.yml packetbeat-$(VERSION)/
 	cp etc/packetbeat.template.json packetbeat-$(VERSION)/
 	tar czvf packetbeat-$(VERSION)-$(ARCH).tar.gz packetbeat-$(VERSION)
 
 .PHONY: darwin_dist
-darwin_dist: packetbeat
+darwin_dist: packetbeat-$(VERSION)
 	mkdir packetbeat-$(VERSION)-darwin
-	cp packetbeat packetbeat-$(VERSION)-darwin
+	cp packetbeat-$(VERSION) packetbeat-$(VERSION)-darwin
 	cp etc/packetbeat.yml packetbeat-$(VERSION)-darwin/
 	cp etc/packetbeat.template.json packetbeat-$(VERSION)-darwin/
 	sed -i .bk 's/device: any/device: en0/' packetbeat-$(VERSION)-darwin/packetbeat.yml
@@ -98,5 +93,4 @@
 
 .PHONY: clean
 clean:
-	rm packetbeat || true
 	rm -r packetbeat-$(VERSION) || true
