--- Makefile	2015-09-11 11:25:07.975309868 +0300
+++ Makefile	2015-09-11 11:25:11.967187971 +0300
@@ -11,9 +11,6 @@
 	go get github.com/tools/godep
 	$(GODEP) go build
 
-go-daemon/god: go-daemon/god.c
-	make -C go-daemon
-
 .PHONY: with_pfring
 with_pfring:
 	go build --tags havepfring
@@ -39,25 +36,23 @@
 	$(GODEP) update ...
 
 .PHONY: install
-install: packetbeat go-daemon/god
-	install -D packetbeat $(DESTDIR)/$(BIN_PATH)/packetbeat
-	install -D go-daemon/god $(DESTDIR)/$(BIN_PATH)/packetbeat-god
+install: packetbeat-$(VERSION)
+	install -D packetbeat-$(VERSION) $(DESTDIR)/$(BIN_PATH)/packetbeat
 	install -m 644 -D etc/packetbeat.yml $(DESTDIR)/$(CONF_PATH)/packetbeat.yml
 	install -m 644 -D etc/packetbeat.template.json $(DESTDIR)/$(CONF_PATH)/packetbeat.template.json
 
 .PHONY: dist
-dist: packetbeat go-daemon/god
+dist: packetbeat-$(VERSION)
 	mkdir packetbeat-$(VERSION)
-	cp packetbeat packetbeat-$(VERSION)/
-	cp go-daemon/god packetbeat-$(VERSION)/packetbeat-god
+	cp packetbeat-$(VERSION) packetbeat-$(VERSION)/
 	cp etc/packetbeat.yml packetbeat-$(VERSION)/
 	cp etc/packetbeat.template.json packetbeat-$(VERSION)/
 	tar czvf packetbeat-$(VERSION)-$(ARCH).tar.gz packetbeat-$(VERSION)
 
 .PHONY: darwin_dist
-darwin_dist: packetbeat
+darwin_dist: packetbeat-$(VERSION)
 	mkdir packetbeat-$(VERSION)-darwin
-	cp packetbeat packetbeat-$(VERSION)-darwin
+	cp packetbeat-$(VERSION) packetbeat-$(VERSION)-darwin
 	cp etc/packetbeat.yml packetbeat-$(VERSION)-darwin/
 	cp etc/packetbeat.template.json packetbeat-$(VERSION)-darwin/
 	sed -i .bk 's/device: any/device: en0/' packetbeat-$(VERSION)-darwin/packetbeat.yml
@@ -117,5 +112,4 @@
 
 .PHONY: clean
 clean:
-	rm packetbeat || true
 	rm -r packetbeat-$(VERSION) || true
